#!/usr/bin/env python3
"""Regenerates Sources/Keyhop/Dashboard/DisplayFont.swift from the Basteleur files in Assets/Fonts.

The dashboard is one self-contained page with no outside resources, so its display faces travel
inside it as data URLs: Bold for figures and page titles, Moonlight for section headings. The font
files are embedded unmodified, as their license (Assets/Fonts/Basteleur-OFL.txt, SIL Open Font
License 1.1) asks of a Reserved Font Name.

Run from the repository root:

    python3 scripts/embed-font.py
"""
import base64
import pathlib

FONTS = {"bold": "Assets/Fonts/Basteleur-Bold.woff2", "moonlight": "Assets/Fonts/Basteleur-Moonlight.woff2"}
OUTPUT = pathlib.Path("Sources/Keyhop/Dashboard/DisplayFont.swift")


def literal(path):
    encoded = base64.b64encode(pathlib.Path(path).read_bytes()).decode("ascii")
    lines = [encoded[i:i + 120] for i in range(0, len(encoded), 120)]
    return "[\n" + "\n".join(f'        "{line}",' for line in lines) + "\n    ].joined()", len(encoded)


def main():
    parts = []
    for name, path in FONTS.items():
        body, size = literal(path)
        parts.append(f"    /// Basteleur {name.capitalize()} as WOFF2, base64 encoded.\n    static let {name} = {body}\n")
        print(f"{name}: {size} characters")
    OUTPUT.write_text(
        "// Generated by scripts/embed-font.py from Assets/Fonts. Don't edit by hand.\n"
        "// Basteleur by Keussel, SIL Open Font License 1.1: Assets/Fonts/Basteleur-OFL.txt.\n\n"
        "enum DisplayFont {\n" + "\n".join(parts) + "}\n"
    )
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
