#!/usr/bin/env python3
"""Regenerates Sources/Keyhop/Dashboard/DisplayFont.swift from Assets/Fonts/Basteleur-Bold.woff2.

The dashboard is one self-contained page with no outside resources, so its display face travels
inside it as a data URL. The font file is embedded unmodified, as its license (Assets/Fonts/
Basteleur-OFL.txt, SIL Open Font License 1.1) asks of a Reserved Font Name.

Run from the repository root:

    python3 scripts/embed-font.py
"""
import base64
import pathlib

FONT = pathlib.Path("Assets/Fonts/Basteleur-Bold.woff2")
OUTPUT = pathlib.Path("Sources/Keyhop/Dashboard/DisplayFont.swift")


def main():
    encoded = base64.b64encode(FONT.read_bytes()).decode("ascii")
    lines = [encoded[i:i + 120] for i in range(0, len(encoded), 120)]
    OUTPUT.write_text(
        "// Generated by scripts/embed-font.py from Assets/Fonts/Basteleur-Bold.woff2. Don't edit by hand.\n"
        "// Basteleur by Keussel, SIL Open Font License 1.1: Assets/Fonts/Basteleur-OFL.txt.\n\n"
        "enum DisplayFont {\n"
        "    /// Basteleur Bold as WOFF2, base64 encoded, for the dashboard's @font-face.\n"
        "    static let woff2Base64 = [\n"
        + "\n".join(f'        "{line}",' for line in lines)
        + '\n    ].joined()\n}\n'
    )
    print(f"Wrote {OUTPUT} ({len(encoded)} characters)")


if __name__ == "__main__":
    main()
