#!/usr/bin/env python3
"""Writes the package-manager manifests for a release from its SHA256SUMS.

    python3 scripts/render-manifests.py --version 0.7.0 --sums dist/SHA256SUMS

  bucket/keyhop.json                    Scoop
  packaging/arch/PKGBUILD                AUR (keyhop-bin)
  packaging/winget/<version>/*.yaml      winget, ready to submit to microsoft/winget-pkgs

--local-sources points the PKGBUILD at files next to it instead of the GitHub release, so CI can
build it with makepkg before anything is published.
"""

import argparse
import datetime
import json
import pathlib
import textwrap

REPO = "dominikzabcik/keyhop"
DESCRIPTION = "Switch Claude Code, Cursor, Codex and Gemini CLI accounts in one click and track their usage."
ROOT = pathlib.Path(__file__).resolve().parent.parent


def read_sums(path):
    sums = {}
    for line in pathlib.Path(path).read_text().splitlines():
        parts = line.split()
        if len(parts) >= 2:
            sums[parts[-1].lstrip("*")] = parts[0].lower()
    return sums


def download(version, name):
    return f"https://github.com/{REPO}/releases/download/v{version}/{name}"


def scoop(version, sums):
    architectures = {}
    for key, arch in (("64bit", "x86_64"), ("arm64", "arm64")):
        name = f"keyhop-{version}-windows-{arch}.zip"
        if name in sums:
            architectures[key] = {"url": download(version, name), "hash": sums[name]}
    manifest = {
        "version": version,
        "description": DESCRIPTION,
        "homepage": f"https://github.com/{REPO}",
        "license": "MIT",
        "architecture": architectures,
        "extract_dir": f"keyhop-{version}",
        "bin": "keyhop.exe",
        "shortcuts": [["keyhop-tray.exe", "Keyhop", "", "keyhop.ico"]],
        "checkver": "github",
        "autoupdate": {
            "architecture": {
                key: {"url": download("$version", f"keyhop-$version-windows-{arch}.zip")}
                for key, arch in (("64bit", "x86_64"), ("arm64", "arm64")) if key in architectures
            },
            "extract_dir": "keyhop-$version",
            "hash": {"url": download("$version", "SHA256SUMS"), "regex": "$sha256\\s+$basename"},
        },
    }
    return json.dumps(manifest, indent=4) + "\n"


def pkgbuild(version, sums, local):
    lines = []
    for arch in ("x86_64", "aarch64"):
        name = f"keyhop-{version}-linux-{arch}.tar.gz"
        if name not in sums:
            continue
        source = name if local else download("$pkgver", f"keyhop-$pkgver-linux-{arch}.tar.gz")
        lines.append(f'source_{arch}=("{source}")')
        lines.append(f"sha256sums_{arch}=('{sums[name]}')")
    arches = " ".join(f"'{a}'" for a in ("x86_64", "aarch64") if f"keyhop-{version}-linux-{a}.tar.gz" in sums)
    sources = "\n".join(lines)
    return textwrap.dedent(f"""\
        # Maintainer: dominikzabcik <35886301+dominikzabcik@users.noreply.github.com>
        # Generated by scripts/render-manifests.py for each release.
        pkgname=keyhop-bin
        pkgver={version}
        pkgrel=1
        pkgdesc="{DESCRIPTION}"
        arch=({arches})
        url="https://github.com/{REPO}"
        license=('MIT')
        depends=('python-gobject' 'gtk3' 'libayatana-appindicator' 'libnotify' 'libsecret' 'ca-certificates')
        optdepends=('webkit2gtk-4.1: Keyhop window inside the tray instead of a browser window')
        provides=('keyhop')
        conflicts=('keyhop')
        options=('!strip' '!debug')
        {{sources}}

        package() {{
          cd "keyhop-$pkgver"
          install -Dm755 keyhop "$pkgdir/usr/bin/keyhop"
          install -Dm755 keyhop-tray "$pkgdir/usr/bin/keyhop-tray"
          install -Dm644 app.keyhop.Keyhop.desktop "$pkgdir/usr/share/applications/app.keyhop.Keyhop.desktop"
          install -Dm644 app.keyhop.Keyhop.metainfo.xml "$pkgdir/usr/share/metainfo/app.keyhop.Keyhop.metainfo.xml"
          for size in 16 24 32 48 64 128 256 512; do
            install -Dm644 "icons/keyhop-$size.png" "$pkgdir/usr/share/icons/hicolor/${{size}}x${{size}}/apps/app.keyhop.Keyhop.png"
          done
          install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
        }}
        """).replace("{sources}", sources)


def winget(version, sums):
    identifier = "dominikzabcik.Keyhop"
    header = f"PackageIdentifier: {identifier}\nPackageVersion: {version}\n"
    installers = []
    for arch, winget_arch in (("x86_64", "x64"), ("arm64", "arm64")):
        name = f"keyhop-{version}-windows-{arch}.zip"
        if name in sums:
            installers.append(
                f"  - Architecture: {winget_arch}\n"
                f"    InstallerUrl: {download(version, name)}\n"
                f"    InstallerSha256: {sums[name].upper()}\n"
            )
    return {
        f"{identifier}.yaml": header + "DefaultLocale: en-US\nManifestType: version\nManifestVersion: 1.6.0\n",
        f"{identifier}.installer.yaml": header
        + "InstallerType: zip\nNestedInstallerType: portable\nNestedInstallerFiles:\n"
        + f"  - RelativeFilePath: keyhop-{version}\\keyhop.exe\n    PortableCommandAlias: keyhop\n"
        + f"ReleaseDate: {datetime.date.today().isoformat()}\nInstallers:\n"
        + "".join(installers)
        + "ManifestType: installer\nManifestVersion: 1.6.0\n",
        f"{identifier}.locale.en-US.yaml": header
        + "PackageLocale: en-US\nPublisher: dominikzabcik\nPublisherUrl: https://github.com/dominikzabcik\n"
        + "PackageName: Keyhop\n"
        + f"PackageUrl: https://github.com/{REPO}\nLicense: MIT\nLicenseUrl: https://github.com/{REPO}/blob/main/LICENSE\n"
        + f"ShortDescription: {DESCRIPTION}\n"
        + "Tags:\n  - claude\n  - cursor\n  - codex\n  - gemini\n  - accounts\n  - usage\n"
        + "ManifestType: defaultLocale\nManifestVersion: 1.6.0\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--version", required=True)
    parser.add_argument("--sums", required=True)
    parser.add_argument("--out", default=str(ROOT), help="repository root to write into")
    parser.add_argument("--local-sources", action="store_true")
    args = parser.parse_args()

    version = args.version.lstrip("v")
    sums = read_sums(args.sums)
    out = pathlib.Path(args.out)

    (out / "bucket").mkdir(parents=True, exist_ok=True)
    (out / "bucket/keyhop.json").write_text(scoop(version, sums))
    (out / "packaging/arch").mkdir(parents=True, exist_ok=True)
    (out / "packaging/arch/PKGBUILD").write_text(pkgbuild(version, sums, args.local_sources))
    folder = out / "packaging/winget" / version
    folder.mkdir(parents=True, exist_ok=True)
    for name, text in winget(version, sums).items():
        (folder / name).write_text(text)
    print(f"Wrote Scoop, AUR and winget manifests for {version}")


if __name__ == "__main__":
    main()
