#!/usr/bin/env python3
"""Regenerates Sources/Switchr/Tracking/PricingTable.swift from https://models.dev.

Run from the repository root:

    python3 scripts/update-pricing.py
"""
import datetime
import json
import pathlib
import subprocess

PROVIDERS = ["anthropic", "openai", "google", "xai", "deepseek", "moonshotai", "zai"]
OUTPUT = pathlib.Path("Sources/Switchr/Tracking/PricingTable.swift")


def literal(value):
    return "nil" if value is None else f"{float(value):g}"


def main():
    raw = subprocess.run(
        ["curl", "-fsSL", "https://models.dev/api.json"], check=True, capture_output=True
    ).stdout
    catalog = json.loads(raw)

    prices = {}
    for provider in PROVIDERS:
        for model_id, model in catalog.get(provider, {}).get("models", {}).items():
            cost = model.get("cost") or {}
            if "input" not in cost or "output" not in cost:
                continue
            prices.setdefault(model_id.lower().split("/")[-1], cost)

    rows = [
        f'        "{name}": ModelPrice(input: {literal(c["input"])}, output: {literal(c["output"])}, '
        f'cacheRead: {literal(c.get("cache_read"))}, cacheWrite: {literal(c.get("cache_write"))}),'
        for name, c in sorted(prices.items())
    ]
    today = datetime.date.today().isoformat()
    OUTPUT.write_text(
        f"// Generated by scripts/update-pricing.py from models.dev on {today}. Don't edit by hand.\n\n"
        "extension Pricing {\n"
        "    /// Standard API prices in USD per million tokens, keyed by model id.\n"
        "    static let table: [String: ModelPrice] = [\n"
        + "\n".join(rows)
        + "\n    ]\n}\n"
    )
    print(f"Wrote {len(rows)} model prices to {OUTPUT}")


if __name__ == "__main__":
    main()
